// Generated by CoffeeScript 1.6.3
(function() {
  var $buildElems, assert, window;

  window = require('jsdom').jsdom('<html><body></body></html>').createWindow();

  global.$ = require('jquery')(window);

  assert = require('assert');

  require('../jquery.classMatch');

  $buildElems = function() {
    var $root;
    $root = $("<div>");
    $root.append($("<div>").attr("id", "A").addClass("A0").addClass("A1"));
    $root.append($("<div>").attr("id", "B").addClass("B0").addClass("B1"));
    return $root.find('*');
  };

  describe('hasClassMatch', function() {
    var $elems;
    $elems = $buildElems();
    it('should return false when no classes match', function() {
      return assert.ok(!$elems.hasClassMatch(/x/));
    });
    it('should return true when one element has one class that matches', function() {
      return assert.ok($elems.hasClassMatch(/A0/));
    });
    it('should return true when one element has several classes that match', function() {
      return assert.ok($elems.hasClassMatch(/B0/));
    });
    return it('should return true when two elements have classes that match', function() {
      return assert.ok($elems.hasClassMatch(/1/));
    });
  });

  describe('removeClassMatch', function() {
    var $elems;
    $elems = $buildElems();
    return it('should remove matching class', function() {
      $elems.removeClassMatch(/0/);
      assert.equal($elems.filter('#A').attr('class'), "A1");
      return assert.equal($elems.filter('#B').attr('class'), "B1");
    });
  });

}).call(this);
